server:
  port: 9091
spring:
  application:
    name: serviceProvider
eureka:
  instance:
    ip-address: 127.0.0.1
    hostname: serviceProvide2hostname
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app: "service2"
  version: "0.0.1"